# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1360330995);
user_pref("app.update.lastUpdateTime.background-update-timer", 1360330875);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1360331115);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1360334835);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1360330755);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 358400);
user_pref("browser.migration.version", 8);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 2);
user_pref("browser.places.smartBookmarksVersion", 4);
user_pref("browser.preferences.advanced.selectedTabIndex", 1);
user_pref("browser.rights.3.shown", true);
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.startup.homepage_override.buildID", "20130201065344");
user_pref("browser.startup.homepage_override.mstone", "18.0.2");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 14);
user_pref("extensions.enabledAddons", "%7B81BF1D23-5F17-408D-AC6B-BD6DF7CAF670%7D:7.6.0.2,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:18.0.2");
user_pref("extensions.imacros.close-sidebar", false);
user_pref("extensions.imacros.defdatapath", "/Users/achilles/Scripts/serpclicker/iMacros/Datasources");
user_pref("extensions.imacros.defdownpath", "/Users/achilles/Scripts/serpclicker/iMacros/Downloads");
user_pref("extensions.imacros.deflogpath", "/Users/achilles/Scripts/serpclicker/iMacros");
user_pref("extensions.imacros.defsavepath", "/Users/achilles/Scripts/serpclicker/iMacros/Macros");
user_pref("extensions.imacros.prefs-checked", true);
user_pref("extensions.imacros.toolbar-checked", true);
user_pref("extensions.imacros.version", "7.6.0.2");
user_pref("extensions.installCache", "[{\"name\":\"app-system-local\",\"addons\":{\"web2pdfextension@web2pdf.adobedotcom\":{\"descriptor\":\"/Library/Application Support/Mozilla/Extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/web2pdfextension@web2pdf.adobedotcom\",\"mtime\":1346950540000}}},{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/Applications/Firefox.app/Contents/MacOS/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1360168925000}}},{\"name\":\"app-profile\",\"addons\":{\"{81BF1D23-5F17-408D-AC6B-BD6DF7CAF670}\":{\"descriptor\":\"/Users/achilles/Scripts/serpclicker/profiles/2200/extensions/{81BF1D23-5F17-408D-AC6B-BD6DF7CAF670}\",\"mtime\":1360326598000}}}]");
user_pref("extensions.lastAppVersion", "18.0.2");
user_pref("extensions.lastPlatformVersion", "18.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("gecko.buildID", "20130201065344");
user_pref("gecko.mstone", "18.0.2");
user_pref("gfx.blacklist.webgl.msaa", 4);
user_pref("idle.lastDailyNotification", 1360332222);
user_pref("intl.charsetmenu.browser.cache", "UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.proxy.socks", "127.0.0.1");
user_pref("network.proxy.socks_port", 2200);
user_pref("network.proxy.type", 1);
user_pref("places.database.lastMaintenance", 1360332223);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.clients.lastSyncLocal", "0");
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.migrated", true);
user_pref("services.sync.nextSync", 0);
user_pref("services.sync.tabs.lastSync", "0");
user_pref("services.sync.tabs.lastSyncLocal", "0");
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1360332223);
user_pref("toolkit.startup.last_success", 1360330635);
user_pref("toolkit.telemetry.prompted", 2);
user_pref("toolkit.telemetry.rejected", true);
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1362918603);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.180", "");
user_pref("xpinstall.whitelist.add.36", "");
